name: 💹 Financial News API Integration
description: Add real-time financial news functionality
title: "[Feature]: Real-time Financial News API Integration"
labels: ["enhancement", "api", "financial-news"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📰 Financial News Integration Feature
        
        This feature will enable the content generator to access and incorporate real-time financial market news through external APIs.

  - type: textarea
    id: feature_overview
    attributes:
      label: Feature Overview
      value: |
        ### 🎯 Objective
        Integrate financial news APIs to provide up-to-date market information for content generation about:
        - Stock markets
        - Cryptocurrencies
        - Economic indicators
        - Company earnings
        - Market trends
        
        ### 📊 Data Sources to Consider
        - **News API** (newsapi.org) - Free tier: 100 requests/day
        - **Alpha Vantage** (alphavantage.co) - Free tier: 25 requests/day
        - **Finnhub** (finnhub.io) - Free tier: 60 calls/minute
        - **Polygon.io** - Real-time and historical market data
        - **Yahoo Finance API** (unofficial) - Free, no API key required
    validations:
      required: true

  - type: textarea
    id: technical_requirements
    attributes:
      label: Technical Requirements
      value: |
        ### 🔧 Implementation Details
        
        1. **New Module**: `src/models/financial_news_fetcher.py`
           - Fetch news from selected APIs
           - Cache mechanism to avoid rate limits
           - Error handling and fallback sources
        
        2. **RAG Enhancement**: `src/core/rag_engine.py`
           - Add financial news as additional context source
           - Timestamp-based relevance filtering
           - Combine scientific papers + real-time news
        
        3. **Configuration**: Update `config/settings.py`
           - Add API keys for financial news services
           - Configurable news sources
           - Cache TTL settings
        
        4. **UI Updates**: `app.py`
           - New checkbox: "Include real-time market data"
           - Display news sources used
           - Show data freshness timestamp
        
        5. **Prompts**: `config/prompts.py`
           - New template for financial content
           - Cite news sources properly
           - Disclaimer for financial information
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      value: |
        ### ✅ Definition of Done
        
        - [ ] Financial news API client implemented with rate limiting
        - [ ] Integration with RAG engine for context enrichment
        - [ ] Environment variables for API keys added to `.env.example`
        - [ ] Caching mechanism to minimize API calls
        - [ ] Error handling with graceful degradation
        - [ ] UI toggle to enable/disable financial news
        - [ ] Unit tests for API fetcher module
        - [ ] Documentation updated in README.md
        - [ ] Financial disclaimer added to generated content
        - [ ] Code comments in English
        - [ ] Demo video showing financial content generation
    validations:
      required: true

  - type: textarea
    id: example_use_cases
    attributes:
      label: Example Use Cases
      value: |
        ### 📝 Use Case Examples
        
        **Use Case 1: Market Analysis Blog Post**
        - Topic: "Bitcoin price movement today"
        - Context: RAG papers on cryptocurrency + real-time BTC news
        - Output: Blog post with scientific background + current market data
        
        **Use Case 2: Stock Market Social Posts**
        - Topic: "Tesla earnings report"
        - Context: Latest Tesla news from Finnhub + financial papers
        - Output: Twitter thread + LinkedIn post with up-to-date info
        
        **Use Case 3: Economic Indicator Article**
        - Topic: "Inflation trends 2026"
        - Context: Economic papers + latest CPI/inflation news
        - Output: Comprehensive article with recent data
    validations:
      required: false

  - type: textarea
    id: risks_and_considerations
    attributes:
      label: Risks & Considerations
      value: |
        ### ⚠️ Important Considerations
        
        - **Rate Limits**: Free API tiers have strict limits, implement caching
        - **Data Quality**: News APIs may contain noise, need filtering
        - **Legal Disclaimer**: Financial content must include disclaimer
        - **API Reliability**: Implement fallback mechanisms
        - **Cost**: Monitor API usage to avoid unexpected charges
        - **Compliance**: Ensure proper attribution of news sources
    validations:
      required: false

  - type: checkboxes
    id: api_selection
    attributes:
      label: Recommended APIs to Implement
      options:
        - label: News API (newsapi.org) - General financial news
        - label: Finnhub (finnhub.io) - Market data and news
        - label: Alpha Vantage - Stock quotes and news
        - label: Yahoo Finance (unofficial) - Backup source
